export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const SEARCH_USERS_REPO = 'SEARCH_USERS_REPO';
export const GITHUB_REPO_LOADED = 'GITHUB_REPO_LOADED';
export const GITHUB_REPO_ERROR = 'GITHUB_REPO_ERROR';
